// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOm4eDkMT6xHIevVlFFn585LYPSJedHIM',
    appId: '1:256085641929:web:7df3c352b66d12a4c9db18',
    messagingSenderId: '256085641929',
    projectId: 'moviebox-51ec9',
    authDomain: 'moviebox-51ec9.firebaseapp.com',
    storageBucket: 'moviebox-51ec9.firebasestorage.app',
    measurementId: 'G-WTXEYQK6B6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm_ceQrjHIj6JmVn6mlvgrVC_pxAPgfH4',
    appId: '1:256085641929:android:1b79e5c0b4bce994c9db18',
    messagingSenderId: '256085641929',
    projectId: 'moviebox-51ec9',
    storageBucket: 'moviebox-51ec9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOt8eQZcUaWu_eH_4WEIYn0y_dDdLgnJE',
    appId: '1:256085641929:ios:f994ac5b2b563e47c9db18',
    messagingSenderId: '256085641929',
    projectId: 'moviebox-51ec9',
    storageBucket: 'moviebox-51ec9.firebasestorage.app',
    iosBundleId: 'com.example.moviebox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOt8eQZcUaWu_eH_4WEIYn0y_dDdLgnJE',
    appId: '1:256085641929:ios:f994ac5b2b563e47c9db18',
    messagingSenderId: '256085641929',
    projectId: 'moviebox-51ec9',
    storageBucket: 'moviebox-51ec9.firebasestorage.app',
    iosBundleId: 'com.example.moviebox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOm4eDkMT6xHIevVlFFn585LYPSJedHIM',
    appId: '1:256085641929:web:e9f27f216b705ae7c9db18',
    messagingSenderId: '256085641929',
    projectId: 'moviebox-51ec9',
    authDomain: 'moviebox-51ec9.firebaseapp.com',
    storageBucket: 'moviebox-51ec9.firebasestorage.app',
    measurementId: 'G-RYZWZ8DM7W',
  );
}
